#	Dockerfile for python app, located in .../app

FROM python:3.9

COPY requirements.txt .

RUN pip install --upgrade pip && \
	pip install -r requirements.txt

COPY . .

CMD [ "flask", "run", "--host=0.0.0.0", "--port=80" ]
