#	Dockerfile for python app, located in .../app

FROM python:3.9

WORKDIR /app

ENV FLASK_APP=app.py

FLASK_ENV=development

COPY ./requirements.txt .

RUN pip install --upgrade pip && \
	pip install -r requirements.txt

COPY . .

CMD [ "python", "app.py" ]
